(function(f){if(typeof exports==="object"&&typeof module!=="undefined"){module.exports=f()}else if(typeof define==="function"&&define.amd){define([],f)}else{var g;if(typeof window!=="undefined"){g=window}else if(typeof global!=="undefined"){g=global}else if(typeof self!=="undefined"){g=self}else{g=this}g.shipper = f()}})(function(){var define,module,exports;return (function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var _extends=Object.assign||function(e){for(var t=1;t<arguments.length;t++){var n=arguments[t];for(var r in n)Object.prototype.hasOwnProperty.call(n,r)&&(e[r]=n[r])}return e};exports.default=function(){var e=arguments.length>0&&void 0!==arguments[0]?arguments[0]:{},t={},n=function(e){var n=arguments.length>1&&void 0!==arguments[1]?arguments[1]:null;n&&(t[e]=t[e]||{queue:[]},t[e].queue.push(n))},r=function(e){var n=arguments.length>1&&void 0!==arguments[1]?arguments[1]:null,r=!!t[e]&&t[e].queue;r&&r.forEach(function(e){return e(n)})};return _extends({},e,{emit:r,on:n})};
},{}],2:[function(require,module,exports){
(function (global){
function getRequest(e){return e&&global.XDomainRequest&&!/MSIE 1/.test(navigator.userAgent)?new XDomainRequest:global.XMLHttpRequest?new XMLHttpRequest:void 0}function setDefault(e,t,o){e[t]=e[t]||o}var reqfields=["responseType","withCredentials","timeout","onprogress"];exports.ajax=function(e,t){function o(e,o){return function(){a||(t(void 0===u.status?e:u.status,0===u.status?"Error":u.response||u.responseText||o,u),a=!0)}}var r=e.headers||{},n=e.body,s=e.method||(n?"POST":"GET"),a=!1,u=getRequest(e.cors);u.open(s,e.url,!0);var l=u.onload=o(200);u.onreadystatechange=function(){4===u.readyState&&l()},u.onerror=o(null,"Error"),u.ontimeout=o(null,"Timeout"),u.onabort=o(null,"Abort"),n&&(setDefault(r,"X-Requested-With","XMLHttpRequest"),global.FormData&&n instanceof global.FormData||setDefault(r,"Content-Type","application/x-www-form-urlencoded"));for(var i,d=0,f=reqfields.length;d<f;d++)i=reqfields[d],void 0!==e[i]&&(u[i]=e[i]);for(var i in r)u.setRequestHeader(i,r[i]);return u.send(n),u};
}).call(this,typeof global !== "undefined" ? global : typeof self !== "undefined" ? self : typeof window !== "undefined" ? window : {})
},{}],3:[function(require,module,exports){
"use strict";function _interopRequireDefault(e){return e&&e.__esModule?e:{default:e}}Object.defineProperty(exports,"__esModule",{value:!0});var _typeof="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(e){return typeof e}:function(e){return e&&"function"==typeof Symbol&&e.constructor===Symbol&&e!==Symbol.prototype?"symbol":typeof e},_loop=require("loop.js"),_loop2=_interopRequireDefault(_loop),_ajax=require("./lib/ajax"),_response=require("./lib/response"),_utils=require("./lib/utils");if("object"!==_typeof(window.Countries))throw new Error("The global Countries object required by your shipping calculator does not exist.");exports.default=function(e){var t=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{},r=t.defaultCountry||null,o=t.endpoints||{prepare:"/cart/prepare_shipping_rates",get:"/cart/async_shipping_rates"},n=e.querySelector('[name="country"]'),i=e.querySelector('[name="province"]'),u=e.querySelector('[name="zip"]'),s=e.querySelector('[type="submit"]'),a={get country(){return n.value},get province(){return i.value},get zip(){return u.value},get meta(){return Countries[this.country]}},c=Object.create((0,_loop2.default)(),{getState:{value:function(){return a}}});return n.addEventListener("change",function(e){var t=Countries[a.country],r=t.provinces,o=t.zip_required;r?((0,_utils.updateSelectOptions)(i,r),i.disabled=!1):(i.innerHTML="",i.disabled=!0),o?u.disabled=!1:u.disabled=!0,c.emit("change",a)}),e.addEventListener("submit",function(e){e.preventDefault(),e.returnValue=!1,c.emit("submit",a),s.disabled=!0,(0,_ajax.requestShippingRates)(o.prepare,a,function(e,t,r){var n=e>=200&&e<=300;if(n)(0,_ajax.fetchShippingRates)(o.get,function(e,t,r){var o=(0,_response.formatSuccess)(t);c.emit("success",o)});else{var i=(0,_response.formatError)(t);c.emit("error",i)}s.disabled=!1})}),(0,_utils.updateSelectOptions)(n,Countries,r),(0,_utils.updateSelectOptions)(i,Countries[r||Object.keys(Countries)[0]].provinces),c};
},{"./lib/ajax":4,"./lib/response":5,"./lib/utils":6,"loop.js":1}],4:[function(require,module,exports){
"use strict";function _interopRequireDefault(e){return e&&e.__esModule?e:{default:e}}Object.defineProperty(exports,"__esModule",{value:!0}),exports.fetchShippingRates=exports.requestShippingRates=void 0;var _nanoajax=require("nanoajax"),_nanoajax2=_interopRequireDefault(_nanoajax),toQueryString=function(e){for(var t="",n=Object.keys(e),a=0;a<n.length;a++){var r=n[a],o=e[r];t+=encodeURIComponent("shipping_address["+r+"]")+"="+encodeURIComponent(o)+(a<n.length-1?"&":"")}return t},requestShippingRates=exports.requestShippingRates=function(e,t,n){return _nanoajax2.default.ajax({method:"post",url:e,body:toQueryString(t)},n)},fetchShippingRates=exports.fetchShippingRates=function(e,t){return _nanoajax2.default.ajax({url:e},t)};
},{"nanoajax":2}],5:[function(require,module,exports){
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var formatSuccess=exports.formatSuccess=function(r){var e=JSON.parse(r).shipping_rates;return e?e.map(function(r){return{type:r.name,price:r.price}}):null},formatError=exports.formatError=function(r){for(var e=JSON.parse(r),t=Object.keys(e),o="",n=0;n<t.length;n++){var s=t[n];o+="Error: "+s+" "+e[s][0]+(n!==t.length-1?", ":"")}return o};
},{}],6:[function(require,module,exports){
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var getProvinces=exports.getProvinces=function(e){return e?Countries[e].provinces:null},createOption=function(){var e=arguments.length>0&&void 0!==arguments[0]?arguments[0]:null;if(e){var t=document.createElement("option");return t.value=e,t.innerHTML=e,t}},selectOption=function(e,t){return[].slice.call(t.options).map(function(n,r){n.value===e&&(t.selectedIndex=r)})},updateSelectOptions=exports.updateSelectOptions=function(e,t){var n=arguments.length>2&&void 0!==arguments[2]?arguments[2]:null,r=!!e.options[0]&&e.options[0].value;t=Array.isArray(t)?t:Object.keys(t);var o=!r||t[0]!==r;return o&&(e.innerHTML="",t.forEach(function(t){return e.appendChild(createOption(t))})),n&&selectOption(n,e),e.value};
},{}]},{},[3])(3)
});